"use client";

import { useState } from "react";
import { UpdateSiteSettingsDto } from "@/lib/api";
import ColorPicker from "@/components/admin/ColorPicker";
import { ColorHarmonyService, ColorTheme, ColorImportance } from "@/lib/color-harmony";
import { useLocaleStore } from "@/lib/store";
import { useTranslation } from "@/lib/i18n";

interface ColorThemeTabProps {
  formData: UpdateSiteSettingsDto;
  setFormData: React.Dispatch<React.SetStateAction<UpdateSiteSettingsDto>>;
  t: (key: string) => string;
}

export default function ColorThemeTab({
  formData,
  setFormData,
  t: tProp,
}: ColorThemeTabProps) {
  const { locale } = useLocaleStore();
  const { t: tHook } = useTranslation(locale);
  const t = tHook || tProp;
  const [colorTheme, setColorTheme] = useState<Partial<ColorTheme>>(
    (formData.colorTheme as Partial<ColorTheme>) || {}
  );

  // CRITICAL 색상들
  const criticalColors = {
    primary: colorTheme.primary || formData.primaryColor || "#667eea",
    background: colorTheme.background || "#fafafa",
    textPrimary: colorTheme.textPrimary || "#171717",
  };

  // 색상 변경 핸들러
  const handleColorChange = (key: keyof ColorTheme, value: string) => {
    const newTheme = { ...colorTheme, [key]: value };
    setColorTheme(newTheme);
    
    // CRITICAL 색상 변경 시 자동 생성
    if (key === "primary" || key === "background" || key === "textPrimary") {
      const newCritical = {
        primary: newTheme.primary || criticalColors.primary,
        background: newTheme.background || criticalColors.background,
        textPrimary: newTheme.textPrimary || criticalColors.textPrimary,
      };
      
      // 자동 색상 생성
      const autoGenerated = ColorHarmonyService.generateThemeFromCritical(newCritical);
      const mergedTheme = { ...autoGenerated, ...newTheme };
      setColorTheme(mergedTheme);
      setFormData({ ...formData, colorTheme: mergedTheme });
    } else {
      setFormData({ ...formData, colorTheme: newTheme });
    }
  };

  // 조화 색상 제안 가져오기
  const getHarmonySuggestions = (baseColor: string) => {
    return [
      ...ColorHarmonyService.generateHarmoniousColors(baseColor, "analogous"),
      ...ColorHarmonyService.generateHarmoniousColors(baseColor, "complementary"),
    ].slice(0, 4);
  };

  return (
    <div className="bg-surface rounded-2xl shadow-lg p-8 border border-border-light">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-text-primary mb-2">{t("admin.siteSettings.colorTheme.title")}</h2>
        <p className="text-text-secondary">
          {t("admin.siteSettings.colorTheme.description")}
        </p>
      </div>

      {/* CRITICAL 색상 섹션 */}
      <div className="mb-8 p-6 bg-error/10 border border-error/30 rounded-lg">
        <h3 className="text-lg font-semibold text-error mb-4">
          {t("admin.siteSettings.colorTheme.critical")}
        </h3>
        <p className="text-sm text-error/80 mb-4">
          {t("admin.siteSettings.colorTheme.criticalDescription")}
        </p>
        <div className="space-y-4">
          <ColorPicker
            label="Primary (메인 브랜드 색상)"
            value={colorTheme.primary || criticalColors.primary}
            onChange={(value) => handleColorChange("primary", value)}
            importance={ColorImportance.CRITICAL}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Background (메인 배경)"
            value={colorTheme.background || criticalColors.background}
            onChange={(value) => handleColorChange("background", value)}
            importance={ColorImportance.CRITICAL}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.textPrimary || criticalColors.textPrimary}
          />
          <ColorPicker
            label="Text Primary (주요 텍스트)"
            value={colorTheme.textPrimary || criticalColors.textPrimary}
            onChange={(value) => handleColorChange("textPrimary", value)}
            importance={ColorImportance.CRITICAL}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.background || criticalColors.background}
          />
        </div>
      </div>

      {/* HIGH 중요도 색상 */}
      <div className="mb-8 p-6 bg-warning/10 border border-warning/30 rounded-lg">
        <h3 className="text-lg font-semibold text-warning mb-4">
          {t("admin.siteSettings.colorTheme.high")}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <ColorPicker
            label="Secondary"
            value={colorTheme.secondary || ""}
            onChange={(value) => handleColorChange("secondary", value)}
            importance={ColorImportance.HIGH}
            criticalColors={criticalColors}
            suggestions={getHarmonySuggestions(criticalColors.primary)}
          />
          <ColorPicker
            label="Background Secondary"
            value={colorTheme.backgroundSecondary || ""}
            onChange={(value) => handleColorChange("backgroundSecondary", value)}
            importance={ColorImportance.HIGH}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.textPrimary || criticalColors.textPrimary}
          />
          <ColorPicker
            label="Surface"
            value={colorTheme.surface || ""}
            onChange={(value) => handleColorChange("surface", value)}
            importance={ColorImportance.HIGH}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.textPrimary || criticalColors.textPrimary}
          />
          <ColorPicker
            label="Text Secondary"
            value={colorTheme.textSecondary || ""}
            onChange={(value) => handleColorChange("textSecondary", value)}
            importance={ColorImportance.HIGH}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.background || criticalColors.background}
          />
          <ColorPicker
            label="Button Primary"
            value={colorTheme.buttonPrimary || ""}
            onChange={(value) => handleColorChange("buttonPrimary", value)}
            importance={ColorImportance.HIGH}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Button Text"
            value={colorTheme.buttonText || "#ffffff"}
            onChange={(value) => handleColorChange("buttonText", value)}
            importance={ColorImportance.HIGH}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.buttonPrimary || criticalColors.primary}
          />
        </div>
      </div>

      {/* MEDIUM 중요도 색상 */}
      <div className="mb-8 p-6 bg-info/10 border border-info/30 rounded-lg">
        <h3 className="text-lg font-semibold text-info mb-4">
          {t("admin.siteSettings.colorTheme.medium")}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <ColorPicker
            label="Accent"
            value={colorTheme.accent || ""}
            onChange={(value) => handleColorChange("accent", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
            suggestions={ColorHarmonyService.generateHarmoniousColors(criticalColors.primary, "complementary")}
          />
          <ColorPicker
            label="Link"
            value={colorTheme.link || ""}
            onChange={(value) => handleColorChange("link", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.background || criticalColors.background}
          />
          <ColorPicker
            label="Border"
            value={colorTheme.border || ""}
            onChange={(value) => handleColorChange("border", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Text Inverse"
            value={colorTheme.textInverse || "#ffffff"}
            onChange={(value) => handleColorChange("textInverse", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.primary || criticalColors.primary}
          />
          <ColorPicker
            label="Button Secondary"
            value={colorTheme.buttonSecondary || ""}
            onChange={(value) => handleColorChange("buttonSecondary", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
            suggestions={getHarmonySuggestions(criticalColors.primary)}
          />
          <ColorPicker
            label="Success"
            value={colorTheme.success || "#10b981"}
            onChange={(value) => handleColorChange("success", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Error"
            value={colorTheme.error || "#ef4444"}
            onChange={(value) => handleColorChange("error", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Warning"
            value={colorTheme.warning || "#f59e0b"}
            onChange={(value) => handleColorChange("warning", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Info"
            value={colorTheme.info || "#3b82f6"}
            onChange={(value) => handleColorChange("info", value)}
            importance={ColorImportance.MEDIUM}
            criticalColors={criticalColors}
          />
        </div>
      </div>

      {/* LOW 중요도 색상 */}
      <div className="mb-8 p-6 bg-surface-hover border border-border rounded-lg">
        <h3 className="text-lg font-semibold text-text-primary mb-4">
          {t("admin.siteSettings.colorTheme.low")}
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <ColorPicker
            label="Surface Hover"
            value={colorTheme.surfaceHover || ""}
            onChange={(value) => handleColorChange("surfaceHover", value)}
            importance={ColorImportance.LOW}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Text Muted"
            value={colorTheme.textMuted || ""}
            onChange={(value) => handleColorChange("textMuted", value)}
            importance={ColorImportance.LOW}
            criticalColors={criticalColors}
            validateAgainst={colorTheme.background || criticalColors.background}
          />
          <ColorPicker
            label="Border Light"
            value={colorTheme.borderLight || ""}
            onChange={(value) => handleColorChange("borderLight", value)}
            importance={ColorImportance.LOW}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Border Dark"
            value={colorTheme.borderDark || ""}
            onChange={(value) => handleColorChange("borderDark", value)}
            importance={ColorImportance.LOW}
            criticalColors={criticalColors}
          />
          <ColorPicker
            label="Link Hover"
            value={colorTheme.linkHover || ""}
            onChange={(value) => handleColorChange("linkHover", value)}
            importance={ColorImportance.LOW}
            criticalColors={criticalColors}
          />
        </div>
      </div>

      {/* 실시간 미리보기 */}
      <div className="mt-8 p-6 bg-surface-hover border border-border rounded-lg">
        <h3 className="text-lg font-semibold text-text-primary mb-4">{t("admin.siteSettings.colorTheme.preview")}</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div
            className="p-4 rounded-lg border-2"
            style={{
              backgroundColor: colorTheme.surface || criticalColors.background,
              borderColor: colorTheme.border || "#e5e7eb",
            }}
          >
            <h4
              className="text-lg font-bold mb-2"
              style={{ color: colorTheme.textPrimary || criticalColors.textPrimary }}
            >
              {t("admin.siteSettings.colorTheme.previewTitle")}
            </h4>
            <p
              className="text-sm mb-4"
              style={{ color: colorTheme.textSecondary || "#6b7280" }}
            >
              {t("admin.siteSettings.colorTheme.previewSubtext")}
            </p>
            <button
              className="px-4 py-2 rounded-lg text-white font-medium"
              style={{ backgroundColor: colorTheme.buttonPrimary || criticalColors.primary }}
            >
              {t("admin.siteSettings.colorTheme.previewButton")}
            </button>
          </div>
          <div
            className="p-4 rounded-lg border-2"
            style={{
              backgroundColor: colorTheme.background || criticalColors.background,
              borderColor: colorTheme.border || "#e5e7eb",
            }}
          >
            <a
              href="#"
              className="text-sm font-medium underline"
              style={{ color: colorTheme.link || criticalColors.primary }}
            >
              {t("admin.siteSettings.colorTheme.previewLink")}
            </a>
            <div className="mt-4 space-y-2">
              <div
                className="px-3 py-1 rounded text-xs"
                style={{ backgroundColor: colorTheme.success || "#10b981", color: "white" }}
              >
                Success
              </div>
              <div
                className="px-3 py-1 rounded text-xs"
                style={{ backgroundColor: colorTheme.error || "#ef4444", color: "white" }}
              >
                Error
              </div>
            </div>
          </div>
          <div
            className="p-4 rounded-lg"
            style={{ backgroundColor: colorTheme.primary || criticalColors.primary }}
          >
            <p
              className="text-sm font-medium"
              style={{ color: colorTheme.buttonText || "#ffffff" }}
            >
              {t("admin.siteSettings.colorTheme.previewPrimaryText")}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

